server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: examplo
      database: hexagonal

arantes:
  client:
    address:
      url: http://localhost:8082/address